# Generated by Django 5.0.4 on 2024-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_username_answer_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="user_email", new_name="user",
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(max_length=255),
        ),
    ]
