# Generated by Django 5.0.6 on 2024-06-20 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_answer_options_remove_answer_user_answer_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer", options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
