# Generated by Django 5.0.6 on 2024-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_answer_options_answer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
